### ISSUE TITLE
Node package manager throwing "UnhandledMatchError" exception when "none" is selected

### ISSUE THREAD

**Issue by aliihsansepar** [blamebutton/laravel-docker-builder#6]
- ![image](https://user-images.githubusercontent.com/38309817/213761442-27b4dc85-bf33-4134-b155-58b98044fc0c.png)

As seen in the image above I select the Node package manager as `none` and an `UnhandledMatchError` exception is thrown as seen in the image below.

- ![image](https://user-images.githubusercontent.com/38309817/213762843-102c6d2d-0bee-44d7-b085-c74428b7d9e2.png)

It's a bug that can be fixed simply but i can open a PR for it if you want. Have a nice day.

**Comment by bram-pkg** [comment]
Oops, how do I not have a test for this!
I'll add a test and fix the code. Thank you for your issue!

**Comment by bram-pkg** [comment]
Should be fixed in [0.1.4](https://github.com/blamebutton/laravel-docker-builder/releases/tag/0.1.4) :smile:
